


#pragma once

#ifndef IOCTL_H_
#define IOCTL_H_

#include "pch.h"

#define KEYLOGGER_READ_IOCTL CTL_CODE(FILE_DEVICE_KEYBOARD, 0x801, METHOD_BUFFERED, FILE_READ_ACCESS)
#define KEYLOGGER_WRITE_IOCTL CTL_CODE(FILE_DEVICE_KEYBOARD, 0x802, METHOD_BUFFERED, FILE_WRITE_ACCESS)

#endif // !IOCTL_H_
